### ISSUE TITLE
Add support for new dotnet core version-less dependency

### ISSUE THREAD

**Issue by JohannBlais** [chwebdude/DependencyChecker#4]
Hi,

Here is the error we get when using the new package versioning for Microsoft.AspNetCore.App

Cheers
Johann

Checking package Microsoft.AspNetCore.App
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Value cannot be null or an empty string.
Parameter name: value
   at NuGet.Versioning.NuGetVersion.Parse(String value)
   at NuGet.Versioning.NuGetVersion..ctor(String version)
   at DependencyChecker.MyClass.<RunAsync>d__2.MoveNext() in D:\Users\i00202849\Documents\Visual Studio 2017\Projects\BadgeCreator\DependencyChecker\Program.cs:line 153
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DependencyChecker.MyClass.Run(Options options) in D:\Users\i00202849\Documents\Visual Studio 2017\Projects\BadgeCreator\DependencyChecker\Program.cs:line 64
   at DependencyChecker.Program.Main(String[] args) in D:\Users\i00202849\Documents\Visual Studio 2017\Projects\BadgeCreator\DependencyChecker\Program.cs:line 47

**Comment by chwebdude** [comment]
Hi
I changed a lot in the last release. But I think I fixed the error. Could you try it againg? If your prolem still appears, could you provide me the csproj file (at least the part with the packages)?

**Comment by chwebdude** [comment]
Could you fix the issue? I just released a new Version 1.4.0. Please check it out. It should work way better.
